name: kidsdom
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

  flutter_tts: ^4.2.3
  android_intent_plus: ^5.3.1

  speech_to_text: ^7.3.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0

  cupertino_icons: ^1.0.8
  go_router: ^14.6.2

  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.10
  firebase_app_check: ^0.2.1+8
  firebase_storage: ^11.6.5

  cached_network_image: ^3.4.1
  provider: ^6.1.5+1

  shared_preferences: ^2.3.3

  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
